# Generated by Django 4.2 on 2023-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_remove_contacts_user_contacts_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice_configurations',
            name='send_mail_to_partner',
            field=models.BooleanField(default=False),
        ),
    ]
