# Generated by Django 4.2 on 2023-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_exercice_configurations_send_mail_to_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice_configurations',
            name='number_day_send',
            field=models.TextField(null=True),
        ),
    ]
