# Generated by Django 4.2 on 2023-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_alter_exercice_configurations_number_day_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='send_date',
            field=models.DateField(null=True),
        ),
    ]
